# Завдання 1

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [1]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9 ,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [2]:
a = np.zeros((2, 3), dtype=int)
a

array([[0, 0, 0],
       [0, 0, 0]])

3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [3]:
a = np.random.randint(1, 10, size=(5, 5))
a

array([[3, 6, 3, 8, 2],
       [6, 7, 9, 7, 5],
       [2, 3, 3, 9, 5],
       [6, 5, 6, 4, 7],
       [4, 4, 8, 6, 4]])

4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [4]:
a = np.random.random((4, 4))
a

array([[0.04838195, 0.61225196, 0.34298886, 0.80210365],
       [0.43440446, 0.29898505, 0.81473711, 0.32453147],
       [0.23786205, 0.63736704, 0.12266325, 0.02511743],
       [0.73487379, 0.71793394, 0.10298812, 0.85615147]])

5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [5]:
a = np.random.randint(1, 10, (5,))
b = np.random.randint(1, 10, (5,))
print(f"sum {a + b}")
print(f"substraction {a - b}")
print(f"multiply {a * b}")

sum [13 14 10  6 11]
substraction [ 3  4  6 -2  5]
multiply [40 45 16  8 24]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [6]:
a = np.array([1, 2, 3, 4, 5, 6, 7])
b = np.array([7, 6, 5, 4, 3, 2, 1])
a @ b

np.int64(84)

7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [7]:
a = np.random.randint(1, 10, size=(2, 3))
b = np.random.randint(1, 10, size=(3, 3))
a @ b

array([[66, 87, 80],
       [34, 69, 58]])

8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [8]:
a = np.random.randint(1, 10, size=(3, 3))
np.linalg.inv(a)

array([[ 0.18644068, -0.34745763,  0.19491525],
       [ 0.15254237,  0.03389831, -0.06779661],
       [-0.22033898,  0.22881356,  0.04237288]])

9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [9]:
a = np.random.randint(1, 10, size=(4, 4))
b = a.T
a, b

(array([[5, 4, 6, 9],
        [7, 2, 1, 6],
        [2, 4, 6, 4],
        [8, 8, 6, 6]]),
 array([[5, 7, 2, 8],
        [4, 2, 4, 8],
        [6, 1, 6, 6],
        [9, 6, 4, 6]]))

10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [10]:
a = np.random.randint(1, 10, size=(3, 4))
b = np.random.randint(1, 10, size=(4,))
a, b, a * b

(array([[3, 6, 7, 5],
        [3, 5, 5, 3],
        [4, 8, 8, 3]]),
 array([9, 6, 7, 8]),
 array([[27, 36, 49, 40],
        [27, 30, 35, 24],
        [36, 48, 56, 24]]))

11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [11]:
a = np.random.random((2, 3))
b = np.random.random(3)
a, b, a * b

(array([[0.99387706, 0.37459647, 0.950973  ],
        [0.94668694, 0.05940073, 0.19668165]]),
 array([0.19402657, 0.73790251, 0.45814799]),
 array([[0.19283855, 0.27641567, 0.43568637],
        [0.18368242, 0.04383195, 0.0901093 ]]))

12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [12]:
a = np.random.randint(1, 10, size=(2, 2))
b = np.random.randint(1, 10, size=(2, 2))
a, b, a * b

(array([[5, 6],
        [9, 6]]),
 array([[7, 9],
        [9, 2]]),
 array([[35, 54],
        [81, 12]]))

13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [13]:
a = np.random.randint(1, 10, size=(2, 2))
b = np.random.randint(1, 10, size=(2, 2))
a, b, a @ b

(array([[3, 6],
        [8, 3]]),
 array([[5, 6],
        [1, 7]]),
 array([[21, 60],
        [43, 69]]))

14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [14]:
a = np.random.randint(1, 100, size=(5, 5))
a.prod()

np.int64(850149266839044096)

15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [15]:
a = np.random.randint(1, 10, size=(4, 4))
b = np.random.randint(1, 10, size=(4, 4))
a - b

array([[ 4,  3,  0,  3],
       [-1,  3, -6,  5],
       [-8, -2, -4, -2],
       [ 3, -1, -6,  3]])

16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [16]:
a = np.random.random((3, 3))
a, a.sum(axis=1, keepdims=True)

(array([[0.67989698, 0.17253922, 0.87853697],
        [0.16674572, 0.71011994, 0.2063501 ],
        [0.61367215, 0.09171924, 0.32288029]]),
 array([[1.73097317],
        [1.08321576],
        [1.02827169]]))

17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [17]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=int)
a, a ** 2

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]]))

18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [18]:
a = np.random.randint(1, 50, size=(4, ))
a, a ** 0.5

(array([40, 39, 37, 38]),
 array([6.32455532, 6.244998  , 6.08276253, 6.164414  ]))

# Завдання 2

1. Замініть усі непарні числа в arr на -1 arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 != 0] = - 1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

2. Створіть та перетворіть 1D-масив на 2D-масив із 2 рядками

In [20]:
a = np.array([1, 2, 3, 4, 5, 6])
a.reshape((2, 3))

array([[1, 2, 3],
       [4, 5, 6]])

3. Створіть два двовимірні масиви а і b, та складіть масиви їх вертикально

In [21]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])
np.concatenate((a, b), axis=0)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

4. Створіть наступний шаблон без жорсткого кодування(Hard coding) . Використовуйте лише функції Numpy і наведений нижче масив введення 

In [22]:
a = np.array([1,2,3])
b = np.repeat(a, 3)
c = np.tile(a, 3)
np.concatenate((b, c))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

5. Отримайте спільні елементи між a і b

In [23]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a, b)

array([2, 4])

6. Отримайте позиції перших 5 максимальних значень у заданому масиві a

In [24]:
np.random.seed(100)
a = np.random.uniform(1,50, 20)
b = np.argsort(a)
b[-5:]

array([18,  7,  3, 10, 15])

7. Вилучіть усі значення NaN із одновимірного масиву

In [25]:
а = np.array([1,2,3,np.nan,5,6,7,np.nan])
a[~np.isnan(a)]


array([27.62684215, 14.64009987, 21.80136195, 42.39403048,  1.23122395,
        6.95688692, 33.86670515, 41.466785  ,  7.69862289, 29.17957314,
       44.67477576, 11.25090398, 10.08108276,  6.31046763, 11.76517714,
       48.95256545, 40.77247431,  9.42510962, 40.99501269, 14.42961361])

8. Обчисліть евклідову відстань між двома масивами a і b.

In [26]:
a = np.array([1,2,3,4,5]) 
b = np.array([4,5,6,7,8])
np.sqrt(np.sum((a - b)**2))

np.float64(6.708203932499369)

9. Знайдіть індекс 5-го повторення числа 1 у масиві x

In [27]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
indices_of_ones = np.where(x == 1)[0]
indices_of_ones[4]

np.int64(8)

10. Знайдіть повторювані записи (від 2-го випадку повторення і далі) у заданому масиві і позначте їх як True. Перше повторення має бути False.

In [28]:
np.random.seed(100)
a = np.random.randint(0, 5, 10)
_, first_indices = np.unique(a, return_index=True)
b = np.full(a.shape, True)
b[first_indices] = False
b

array([False,  True, False,  True, False, False,  True,  True,  True,
        True])